'use strict';
(() => {
  const base=window.TIBET_BASE, guide=window.TIBET_ITINERARY, weather=window.TIBET_WEATHER, research=window.TIBET_RESEARCH;
  const media={...window.TIBET_MEDIA.assets,...window.TIBET_HOTEL_MEDIA.assets,...window.TIBET_EXTRA_MEDIA.assets};
  const hotelMedia=window.TIBET_HOTEL_MEDIA.hotels;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lines=v=>esc(v).replace(/\n/g,'<br>');
  const link=(url,label,cls='')=>`<a href="${esc(url)}" class="${cls}" target="_blank" rel="noopener noreferrer">${label}</a>`;
  const findAsset=name=>Object.values(media).find(a=>a.name===name || (a.aliases||[]).includes(name));
  const hotelLink=h=>hotelMedia[h.hotel]?.url?link(hotelMedia[h.hotel].url,esc(h.hotel),'hotel-link'):esc(h.hotel);
  const hotelsForDate=date=>base.hotels.filter(h=>h.checkin.split('\n').includes(date));
  const hotelPhotoId=(h,day)=>`hotel-photo-${base.hotels.indexOf(h)}-${day}`;
  const firstHotelDay=h=>guide.days.find(d=>h.checkin.split('\n').includes(d.date))?.day;
  const weatherFor=day=>weather.nodes.filter(n=>n.day===day);
  const hasWeather=n=>['forecast','long_range_trend'].includes(n.status)&&Number.isFinite(n.high)&&Number.isFinite(n.low);
  const isTrend=n=>n.status==='long_range_trend';
  const staleTrend=n=>isTrend(n)&&String(n.checkedAt).slice(0,10)<String(weather.checkedAt).slice(0,10);
  const weatherKind=n=>isTrend(n)?`MSN · 30 天远期趋势（${staleTrend(n)?'保留旧快照':'本次已核验'}）`:'墨迹 · 15 天预报';
  const weatherChecked=n=>String(n.checkedAt||weather.checkedAt).slice(0,16).replace('T',' ');
  const trendDescription=n=>`${n.date.slice(5).replace('-','.')} ${n.places.join(' / ')}（${staleTrend(n)?'旧快照，原核对':'本次核对'} ${weatherChecked(n)}）`;
  const wxClass=c=>!c||/待更新|待核实/.test(c)?'unknown':/雷/.test(c)?'storm':/雪/.test(c)?'snow':/雨/.test(c)?'rain':/阴/.test(c)?'overcast':/云/.test(c)?'cloud':'sun';
  const wxRank={unknown:0,sun:0,cloud:1,overcast:2,rain:3,snow:4,storm:5};
  const wxLabel={unknown:'天气状态待核实',sun:'晴',cloud:'多云',overcast:'阴',rain:'雨',snow:'雨雪',storm:'雷雨'};
  function wxIcon(condition,size=30){
    if(wxClass(condition)==='unknown') return `<svg class="wx-icon" width="${size}" height="${size}" viewBox="0 0 40 40" role="img" aria-label="天气状态待核实"><circle cx="20" cy="20" r="13" fill="none" stroke="#8f998d" stroke-width="1.5" stroke-dasharray="3 3"/><text x="20" y="25" text-anchor="middle" fill="#8f998d" font-size="17">?</text></svg>`;
    const k=wxClass(condition),sun='<circle cx="19" cy="17" r="8" fill="#e7b550"/><path d="M19 3v3m0 22v3M5 17h3m22 0h3M9 7l2 2m16 16 2 2M9 27l2-2M27 9l2-2" stroke="#e7b550" stroke-width="2" stroke-linecap="round"/>',cloud='<path d="M10 27a7 7 0 0 1 0-14 10 10 0 0 1 18-1 8 8 0 1 1 2 15Z" fill="#c7d6d3" stroke="#7c9993" stroke-width="1.2"/>',rain='<path d="m12 30-2 5m11-5-2 5m11-5-2 5" stroke="#568cb1" stroke-width="2" stroke-linecap="round"/>',snow='<text x="11" y="38" font-size="14" fill="#568cb1">❄</text>',storm='<path d="m21 25-6 8h5l-2 6 9-10h-6l3-4" fill="#d89b3b"/>';
    return `<svg class="wx-icon" width="${size}" height="${size}" viewBox="0 0 40 40" role="img" aria-label="${esc(condition)}">${k==='sun'?sun:(k==='cloud'?sun:'')+cloud}${k==='rain'?rain:k==='snow'?snow:k==='storm'?storm:''}</svg>`;
  }
  function dayWeather(day){const all=weatherFor(day),valid=all.filter(hasWeather);if(!valid.length)return {available:false,condition:'待更新',text:'超出当前预报范围'};const worst=valid.reduce((a,n)=>wxRank[wxClass(n.condition)]>wxRank[wxClass(a.condition)]?n:a,valid[0]),trend=valid.some(isTrend),condition=valid.some(n=>wxClass(n.condition)==='unknown')?'天气状态待核实':worst.condition;return {available:true,high:Math.max(...valid.map(n=>n.high)),low:Math.min(...valid.map(n=>n.low)),condition,trend,partial:valid.length!==all.length,text:`${trend?'MSN 远期趋势 · ':''}${wxLabel[wxClass(condition)]} · ${valid.length!==all.length?'部分地点参考':'沿线参考范围'}`};}
  const rangeHtml=w=>`<div class="weather-range">${wxIcon(w.condition)}${w.available?`<span class="temp-stack"><span class="temp-high">${w.high}°C</span><span class="temp-low">${w.low}°C</span></span>`:'<span class="wx-summary">待更新</span>'}</div>`;
  function renderOverview(){
    $('overview-content').innerHTML=`<table class="overview-table"><thead><tr><th>日期</th><th>主要路线 / 节奏</th><th>住宿</th><th>天气温度</th><th>穿衣 / 随身重点</th></tr></thead><tbody>${guide.days.map(d=>{const w=dayWeather(d.day);return `<tr><td data-label="日期"><b>${d.date}</b><small class="date-day">${d.day} · ${d.weekday}</small></td><td data-label="路线"><div><p><a href="#day-${d.day}"><b>${d.route.join(' → ')}</b></a></p><small>${esc(d.pace)}</small></div></td><td data-label="住宿"><div>${d.hotelIndexes.length?d.hotelIndexes.map(i=>`${hotelLink(base.hotels[i])}${base.hotels[i].alert?` <span class="hotel-alert">（${esc(base.hotels[i].alert)}）</span>`:''}`).join('<br>'):'返程'}<small>${d.stay==='—'?'':esc(d.stay)}</small></div></td><td data-label="天气"><div>${rangeHtml(w)}<small>${esc(w.text)}</small></div></td><td data-label="穿衣"><div><p>${esc(d.clothing)}</p><small>随身：${esc(d.carry)}</small></div></td></tr>`;}).join('')}</tbody></table>`;
  }
  function mergedWeatherNodes(){
    const out=[];
    for(const n of weather.nodes){
      const prev=out.at(-1),valid=hasWeather(n);
      const can=prev&&valid&&hasWeather(prev)&&n.status===prev.status&&n.provider===prev.provider&&n.date===prev.date&&wxClass(n.condition)===prev.category&&Math.max(n.high,...prev.members.map(m=>m.high))-Math.min(n.high,...prev.members.map(m=>m.high))<=2&&Math.max(n.low,...prev.members.map(m=>m.low))-Math.min(n.low,...prev.members.map(m=>m.low))<=2;
      if(can){prev.members.push(n);prev.places.push(...n.places);prev.high=Math.max(prev.high,n.high);prev.low=Math.min(prev.low,n.low);}
      else out.push({...n,places:[...n.places],category:wxClass(n.condition),members:[n]});
    }
    return out;
  }
  function wrapLabel(s,max=13){const chars=[...s],out=[];for(let i=0;i<chars.length;i+=max)out.push(chars.slice(i,i+max).join(''));return out;}
  function renderWeather(){
    const nodes=mergedWeatherNodes(),valid=weather.nodes.filter(hasWeather),trendNodes=valid.filter(isTrend),hasTrends=trendNodes.length>0,w=Math.max(1200,nodes.length*146+95),h=480,left=58,right=30,top=110,bottom=297;
    const lo=valid.length?Math.floor((Math.min(...valid.map(n=>n.low))-2)/5)*5:-5,hi=valid.length?Math.ceil((Math.max(...valid.map(n=>n.high))+2)/5)*5:25;
    const x=i=>left+(i+.5)*(w-left-right)/nodes.length,y=t=>bottom-(t-lo)/(hi-lo)*(bottom-top);
    let svg=`<svg class="weather-svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="weather-title weather-desc"><title id="weather-title">沿途日期与地点高低温曲线</title><desc id="weather-desc">红线最高温，蓝线日最低参考。实线实心点为墨迹预报。${hasTrends?'虚线空心点为 MSN 30 天远期趋势，不同来源不连线；核对时间见逐点来源。':''}缺失值不插值。</desc>`;
    for(let v=lo;v<=hi;v+=5)svg+=`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#d9dfd7" stroke-dasharray="3 5"/><text x="${left-12}" y="${y(v)+4}" text-anchor="end" font-size="11" fill="#7a897f">${v}°</text>`;
    let dayIndex=-1,lastDay='';nodes.forEach((n,i)=>{if(n.day!==lastDay){dayIndex++;lastDay=n.day;}const step=(w-left-right)/nodes.length;svg+=`<rect x="${x(i)-step/2}" y="12" width="${step}" height="450" fill="${dayIndex%2?'#153b3410':'transparent'}"/><text x="${x(i)}" y="34" text-anchor="middle" font-size="12" font-weight="700" fill="#234339">${n.date.slice(5).replace('-','.')} · ${n.day}</text><g transform="translate(${x(i)-17},44)">${wxIcon(n.condition,34)}</g><text x="${x(i)}" y="94" text-anchor="middle" font-size="11" fill="#627569">${isTrend(n)?'MSN · 远期趋势':hasWeather(n)?'墨迹预报':'待更新'}</text>`;});
    for(const field of ['high','low'])for(const status of ['forecast','long_range_trend']){let active=false,path='';nodes.forEach((n,i)=>{if(n.status!==status||!hasWeather(n)){active=false;return;}path+=`${active?'L':'M'}${x(i).toFixed(2)} ${y(n[field]).toFixed(2)} `;active=true;});svg+=`<path class="weather-series" data-status="${status}" d="${path}" fill="none" stroke="${field==='high'?'#bd5d3e':'#427ea7'}" stroke-width="2.6" stroke-linejoin="round"${status==='long_range_trend'?' stroke-dasharray="7 5"':''}/>`;}
    nodes.forEach((n,i)=>{if(hasWeather(n)){for(const field of ['high','low']){const color=field==='high'?'#bd5d3e':'#427ea7';svg+=`<circle cx="${x(i)}" cy="${y(n[field])}" r="4" fill="${isTrend(n)?'#fffaf0':color}" stroke="${color}" stroke-width="1.5"/><text x="${x(i)}" y="${y(n[field])+(field==='high'?-12:21)}" text-anchor="middle" font-size="13" font-weight="700" fill="${field==='high'?'#a45032':'#3a7095'}">${n[field]}°</text>`;}}else svg+=`<text x="${x(i)}" y="196" text-anchor="middle" font-size="12" fill="#8a958d">待更新</text>`;
      const label=[...new Set(n.places)].join(' / ');svg+=`<text x="${x(i)}" y="344" text-anchor="middle" font-size="10" fill="#354f45">${wrapLabel(label).map((t,j)=>`<tspan x="${x(i)}" dy="${j?15:0}">${esc(t)}</tspan>`).join('')}</text><text x="${x(i)}" y="438" text-anchor="middle" font-size="9" fill="#758278">${esc([...new Set(n.members.map(m=>m.wind))].join(' / '))}</text>`;
    });svg+='</svg>';
    $('weather-stamp').innerHTML=`墨迹 · ${esc(weather.checkedAt.slice(0,16).replace('T',' '))}${hasTrends?`<br>MSN 远期趋势 · 核对 ${esc([...new Set(trendNodes.map(weatherChecked))].join(' / '))}`:''}<br>静态快照，页面不自动刷新天气`;
    $('weather-summary').innerHTML=`<div class="weather-note"><div><h3>${hasTrends?'墨迹预报 · 个别地点采用远期趋势':'沿途天气预报'}</h3><p>墨迹明确日期预报范围为 ${esc(weather.forecastRange.from)}—${esc(weather.forecastRange.through)}。${hasTrends?`采用 MSN 30 天远期趋势的地点：${esc(trendNodes.map(trendDescription).join('；'))}。各点核对时间如上，以虚线空心点显示；远期趋势不是短期预报或历史平均值。`:''}沿途温区取各点最高温最大值、最低温最小值；县区代理不等于山口、冰川、湖岸精确温度。蓝线为日最低参考，不是 07:00—24:00 实际最低温。</p></div><span class="weather-badge">${hasTrends?'个别远期趋势 · 临行复核':'分层保暖 · 临行复核'}</span></div>`;
    $('weather-chart').innerHTML=`<div class="chart-scroll" tabindex="0" aria-label="左右滚动查看全程天气曲线">${svg}</div><p class="chart-help"><span><i class="high"></i>最高温</span><span><i class="low"></i>日最低温参考</span><span><i class="forecast-key"></i>墨迹预报</span>${hasTrends?'<span><i class="trend-key"></i>MSN 远期趋势</span>':''}<span>横向滑动看日期和地点 · 仅合并同来源同口径的相近天气</span></p>`;
    $('weather-detail').innerHTML=`<div class="weather-list">${weather.nodes.map(n=>`<article class="weather-source-card" data-status="${esc(n.status)}"><span class="date-day">${n.date} · ${n.day}</span><h4>${esc(n.places.join(' / '))}</h4><b class="weather-kind">${esc(weatherKind(n))}</b><div class="reading">${esc(n.condition)} · ${hasWeather(n)?`<b class="temp-high">${n.high}°C</b> / <b class="temp-low">${n.low}°C</b>`:'待更新'} · ${esc(n.wind)}</div><p>${esc(n.reason)}</p>${n.navigation?`<p>复查：${esc(n.navigation)}</p>`:''}${link(n.sourceUrl,`${esc(n.provider)} · ${esc(n.region)} ↗`)}<p class="weather-checked">${staleTrend(n)?'原核对（本次未更新）：':'核对：'}${esc(weatherChecked(n))}</p></article>`).join('')}</div><p class="micro">“转”表示白天到夜间的变化。${hasTrends?'MSN 未核实的天气文字和风速明确留空，不由温度推断天气。':''}合并仅发生于同日相邻地点、同来源同口径、同天气类别且高低温分别相差不超过 2℃。</p>`;
  }
  function photo(a){
    if(!a?.src||a.requiresPermission||a.display==='source-link')return '';
    return `<div class="photo-wrap"><img src="${esc(a.src)}" alt="${esc(a.alt)}" loading="lazy" decoding="async" referrerpolicy="no-referrer"><div class="photo-fallback" hidden><b>图片暂不可用</b><span>文字攻略仍可阅读</span>${link(a.sourceUrl,'查看原图来源 ↗')}</div>${link(a.sourceUrl,esc(a.credit),'photo-credit')}</div>`;
  }
  function photoContext(a){
    if(!a)return '';
    if(a.name==='珠峰大本营')return '图：珠峰北坡／绒布寺一带，非营地设施实拍。';
    if(a.src==='guide-images/karuola.webp')return '图摄于 2011 年，冰川现状与照片可能不同。';
    if(a.license)return `${a.credit} · 图片经尺寸与格式调整`;
    return '';
  }
  function spotCard(s){const a=findAsset(s.name),xhs=`https://www.xiaohongshu.com/search_result?keyword=${encodeURIComponent(s.name+' 攻略')}`;return `<article class="photo-card">${photo(a)}<div class="photo-caption"><span class="card-tag">${esc(s.priority)} · ${esc(s.duration)}</span><h4>${esc(s.name)}</h4><p>${esc(s.play)}</p>${photoContext(a)?`<p class="photo-context">${esc(photoContext(a))}</p>`:''}${a?.requiresPermission?'<p class="photo-context">图源需转载授权，仅提供原文看图入口。</p>':''}<div class="card-links">${link(xhs,'小红书搜索 ↗','xhs-link')}${a?.sourceUrl?link(a.sourceUrl,a.requiresPermission?'原文看图 ↗':'图片来源 ↗'):''}${a?.licenseUrl?link(a.licenseUrl,'图片许可 ↗'):''}</div></div></article>`;}
  function hotelPhotoFigure(asset,label,room=''){
    const available=asset?.src&&asset.status==='verified';
    return `<figure class="hotel-photo"${room?` data-room="${esc(room)}"`:''}>${available?photo(asset):'<div class="hotel-photo-missing"><span>图片待核实</span><small>未找到能确认对应关系的实拍图，不以其他酒店或房型替代。</small></div>'}<figcaption><b>${esc(label)}</b>${available&&asset.sourceRoomName&&asset.sourceRoomName!==room?`<span>来源房型：${esc(asset.sourceRoomName)}</span>`:''}${available&&asset.matchNote?`<span>${esc(asset.matchNote)}</span>`:''}${available?link(asset.sourceUrl,'查看图片来源 ↗'):''}</figcaption></figure>`;
  }
  function hotelStrip(h,day){
    const entry=hotelMedia[h.hotel],a=media[entry?.image]||findAsset(h.hotel),backup=h.place.endsWith('（备选）');
    const rooms=h.room.split('\n').map(room=>{const item=entry?.rooms?.find(r=>r.room===room);return hotelPhotoFigure(media[item?.image],room,room);}).join('');
    return `<aside class="hotel-strip${backup?' is-backup':''}" id="${hotelPhotoId(h,day)}" data-hotel="${esc(h.hotel)}"><div class="hotel-summary"><p class="eyebrow">${backup?'ALTERNATIVE / 同日备选':'TONIGHT / 今晚住宿'}</p><h4>${hotelLink(h)}${backup?' <span class="hotel-backup">（备选）</span>':''}${h.alert?` <span class="hotel-alert">（${esc(h.alert)}）</span>`:''}</h4><p>${esc(h.place.replace('（备选）',''))} · ${esc(h.span)} · ${lines(h.room)}<br>${esc(h.oxygen)} · 早餐：${esc(h.breakfast)}</p><div class="card-links"><a href="#hotels">查看房价与完整订单 ↗</a></div></div><div class="hotel-photo-grid">${hotelPhotoFigure(a,'酒店外观')}${rooms}</div><p class="hotel-photo-note">房型图片来自酒店公开图库或同房型住客点评；具体楼层、朝向、布置与入住时现状以酒店安排为准。</p></aside>`;
  }
  function renderDays(){
    $('day-nav').innerHTML=guide.days.map(d=>`<a href="#day-${d.day}"><b>${d.day}</b>${d.date}</a>`).join('');
    $('days-content').innerHTML=guide.days.map(d=>{const w=dayWeather(d.day),spots=d.spots.map(k=>guide.spots[k]),photos=spots.filter(s=>s.priority!=='补给'),stops=spots.filter(s=>s.priority==='补给');return `<article class="day-article" id="day-${d.day}"><header class="day-heading"><div class="day-number">${d.day}<small>${d.date} · ${d.weekday}</small></div><div><p class="eyebrow">${esc(d.chapter)}</p><h3>${esc(d.title)}</h3><p class="route-line">${esc(d.route.join(' → '))}</p></div></header><div class="day-meta"><div><p><b>${esc(d.drive)}</b></p>${d.metricNote?`<p class="metric-note">${esc(d.metricNote)}</p>`:''}<small>${esc(d.pace)}</small></div><div class="day-weather">${rangeHtml(w)}<div class="day-weather-text"><b>${esc(w.text)}</b><br>${esc(d.clothing)}</div></div></div>${photos.length?`<div class="photo-grid count-${photos.length}">${photos.map(spotCard).join('')}</div>`:''}${stops.map(s=>`<div class="stop-text"><b>${esc(s.name)} · ${esc(s.duration)}</b><p>${esc(s.play)}</p></div>`).join('')}${hotelsForDate(d.date).map(h=>hotelStrip(h,d.day)).join('')}<div class="schedule" aria-label="${d.day}建议时间安排">${d.schedule.map(row=>`<div class="schedule-row"><time>${esc(row[0])}</time><h4>${esc(row[1])}</h4><p>${esc(row[2])}</p></div>`).join('')}</div><div class="day-decision"><b>当天取舍</b><p>${esc(d.decision)}</p></div></article>`;}).join('');
  }
  function renderHotels(){
    const counts=base.hotels.reduce((m,h)=>m.set(h.checkin,(m.get(h.checkin)||0)+1),new Map()),seen=new Set();
    const rows=base.hotels.map(h=>{const date=seen.has(h.checkin)?'':`<td class="nowrap hotel-date" rowspan="${counts.get(h.checkin)}"><strong>${lines(h.checkin)}</strong></td>`;seen.add(h.checkin);const backup=h.place.endsWith('（备选）'),place=backup?h.place.slice(0,-4):h.place;return `<tr>${date}<td class="nowrap">${esc(h.span)}</td><td>${esc(place)}${backup?' <span class="hotel-backup">（备选）</span>':''}${h.alert?` <span class="hotel-alert">（${esc(h.alert)}）</span>`:''}</td><td class="hotel-name"><strong>${hotelLink(h)}</strong><a class="hotel-photo-jump" href="#${hotelPhotoId(h,firstHotelDay(h))}">外观与房型图片 ↓</a></td><td><strong>${lines(h.price)}</strong></td><td>${lines(h.room)}</td><td class="nowrap">${esc(h.cancel)}</td><td class="nowrap">${lines(h.area)}</td><td>${lines(h.bed)}</td><td>${esc(h.oxygen)}</td><td>${esc(h.breakfast)}</td></tr>`;}).join('');
    $('hotel-grid').innerHTML=`<div class="hotel-table-wrap" tabindex="0" aria-label="可横向滚动的酒店完整信息表"><table class="hotel-table"><thead><tr>${['入住日','晚数 / 间数','地点','酒店名','单间价格','房型','可取消时间','面积','床型','供氧方式','早餐'].map(v=>`<th scope="col">${v}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
  }
  function renderDrone(){
    const drone=window.TIBET_DRONE;
    if(!drone?.rows?.length){$('drone-content').innerHTML='<div class="editor-note"><b>资料待核验</b><p>未取得逐点空域与场地核验记录，不能据此判断适飞。</p></div>';return;}
    const legendVerified=drone.legend?.verified===true;
    const colorsVerified=drone.legend?.colorsVerified===true;
    const zoneNames={blue:'UOM 蓝区',white:'UOM 白区',mixed:'蓝白交界 / 范围混合',unverified:'待核验 · 不作适飞判断'};
    const zoneStatus=row=>colorsVerified&&row.uom?.colorVerified===true&&['blue','white','mixed'].includes(row.uom.status)?row.uom.status:'unverified';
    const sources=(items,label)=>items?.length?`<div class="drone-sources" aria-label="${label}">${items.filter(s=>/^https?:\/\//.test(s.url||'')).map(s=>link(s.url,`${esc(s.title||'来源')} ↗`)).join('')}</div>`:'';
    const dateText=value=>value?String(value).replace('T',' '):'未完成逐点查询';
    const checked=drone.rows.filter(r=>zoneStatus(r)!=='unverified').length;
    const draft=checked<drone.rows.length;
    $('drone-stamp').innerHTML=`${draft?'核验初稿':'资料整理'}：${esc(dateText(drone.checkedAt))}<br>${drone.rows.length} 条逐日记录 · ${checked} 条 UOM 颜色已核验`;
    const legend=colorsVerified?`<div class="drone-legend" aria-label="UOM 页面实见颜色"><span><i class="drone-swatch is-blue"></i>${legendVerified?`蓝色 = ${esc(drone.legend.blue||'UOM 蓝区')}`:'蓝区 · 页面实见蓝色色块'}</span><span><i class="drone-swatch is-white"></i>${legendVerified?`白色 = ${esc(drone.legend.white||'UOM 白区')}`:'白区 · 页面实见白色区域'}</span><span><i class="drone-swatch is-unverified"></i>待核验 ≠ 适飞</span></div>${!legendVerified?'<p>颜色的法律含义尚未完整核验；白区不自动等同法定管制区或可飞区。</p>':''}`:'<p class="drone-legend-pending">UOM 页面色块尚未完成实见核验，暂不填写蓝区 / 白区。</p>';
    const rows=drone.rows.map(row=>{
      const status=zoneStatus(row),location=row.location||{},venue=row.venue||{},uom=row.uom||{};
      const coordinates=Array.isArray(location.coordinates)?location.coordinates.join(', '):location.coordinates;
      const uomLabel=status==='unverified'?(uom.status==='unverified'&&(uom.attempt||uom.observation)?uom.label||zoneNames.unverified:zoneNames.unverified):(uom.label||zoneNames[status]);
      const venueStatus=['restricted','conditional','no_rule_found'].includes(venue.status)?venue.status:'unverified';
      const observation=uom.observation;
      const observationHtml=observation?`<div class="drone-observation"><small>查询词：${esc(observation.queryText||'未记录')}</small><small>匹配结果：${esc(observation.matchedResult||'未记录')}</small><small>地图级别：${esc(observation.zoom??'未记录')}</small>${status!=='unverified'?`<small>观察时间：${esc(dateText(observation.observedAt))}</small>`:''}<small>${status==='unverified'?'尝试说明':'观察说明'}：${esc(observation.note||'未记录')}</small></div>`:'';
      const queryDate=status==='unverified'&&observation?`尝试日期：${dateText(observation.observedAt)}`:`颜色核验：${dateText(uom.checkedAt)}`;
      return `<tr data-drone-id="${esc(row.id)}" data-day="${esc(row.day)}" data-uom-status="${status}"><th scope="row" data-label="日期 / 地点"><a class="drone-day" href="#day-${esc(row.day)}">${esc(row.date)} · ${esc(row.day)}</a><b class="drone-place">${esc(row.place)}</b><p>${esc(location.label||'具体起飞点待定位')}</p><small class="drone-location-precision">定位精度：${esc(location.precision||'待核验')}</small>${coordinates?`<small>参考坐标：${esc(coordinates)}</small>`:''}${location.note?`<small>${esc(location.note)}</small>`:''}</th><td data-label="UOM 空域"><span class="drone-status is-${status}">${esc(uomLabel)}</span><p>${esc(uom.detail||'没有可用于判断此起飞点的 UOM 核验记录。')}</p><small class="drone-query-date">${esc(queryDate)}</small>${observationHtml}${sources(uom.sources,'UOM 核验来源')}</td><td data-label="场地 / 管理"><span class="drone-venue-status is-${venueStatus}">${esc(venue.label||'当地管理待核验')}</span><p>${esc(venue.detail||'未核实场地管理要求；缺少公告不代表允许飞行。')}</p>${sources(venue.sources,'场地管理来源')}</td><td data-label="结论 / 复查"><b class="drone-conclusion">${esc(row.conclusion||'尚不能判断适飞')}</b><p>${esc(row.action||'确定实际起飞点后，重新查询 UOM 并核对现场管理要求。')}</p></td></tr>`;
    }).join('');
    $('drone-content').innerHTML=`<div class="drone-intro"><div><h3>${draft?'核验初稿 · UOM 颜色查询尚未完成':'先看空域，再核对场地。'}</h3><p>${draft?`目前 ${checked} 条 UOM 颜色已核验；场地资料不能代替 UOM 实际点位查询。`:''}UOM 页面颜色与景区、文保及现场管理是独立信息。蓝区和白区均不单独构成放飞许可；未查到限制也不等于允许。</p></div><span class="drone-count">${checked} / ${drone.rows.length}<small>UOM 颜色已核验记录</small></span></div><div class="drone-legend-panel">${legend}${drone.legend?.observedAt?`<p>图例观察：${esc(dateText(drone.legend.observedAt))}</p>`:''}${drone.legend?.note?`<p>${esc(drone.legend.note)}</p>`:''}${sources(drone.legend?.sources,'UOM 图例来源')}</div><div class="drone-table-wrap"><table class="drone-table"><caption>${draft?`核验初稿 · ${checked} 条 UOM 颜色已核验。`:''}按行程逐日列出地点；颜色结果只对应记录中的搜索匹配点与观察时间，实际起飞点和计划飞行范围仍需复查。</caption><colgroup><col class="drone-col-place"><col class="drone-col-uom"><col class="drone-col-venue"><col class="drone-col-action"></colgroup><thead><tr><th scope="col">日期 / 地点与定位</th><th scope="col">UOM 空域查询</th><th scope="col">景区 / 场地管理</th><th scope="col">当次结论 / 下一步</th></tr></thead><tbody>${rows}</tbody></table></div>${drone.notes?.length?`<div class="drone-notes"><h3>使用这张表前</h3><ul>${drone.notes.map(note=>`<li>${esc(note)}</li>`).join('')}</ul></div>`:''}`;
  }
  function renderAltitude(){
    const groups=base.profile,points=groups.flatMap((g,groupIndex)=>g.points.map(p=>({...p,date:g.date,day:g.day,groupIndex}))),width=Math.max(1680,points.length*74+150),height=690,left=74,right=42,plotTop=150,plotBottom=470,labelY=505,plotWidth=width-left-right;
    const x=i=>left+i*plotWidth/(points.length-1),y=a=>plotBottom-(a-3400)/(5400-3400)*(plotBottom-plotTop),coords=points.map((p,i)=>[x(i),y(p.alt)]);
    const line=coords.map(([px,py],i)=>`${i?'L':'M'} ${px.toFixed(1)} ${py.toFixed(1)}`).join(' '),area=`${line} L ${coords.at(-1)[0]} ${plotBottom} L ${coords[0][0]} ${plotBottom} Z`;
    const grid=[3500,4000,4500,5000].map(t=>`<g class="altitude-grid-line"><line x1="${left}" y1="${y(t)}" x2="${width-right}" y2="${y(t)}"/><text x="${left-14}" y="${y(t)+4}" text-anchor="end">${t.toLocaleString()} m</text></g>`).join('');
    let offset=0;const bands=groups.map((g,i)=>{const start=offset,end=offset+g.points.length-1;offset+=g.points.length;const a=start===0?left:(x(start-1)+x(start))/2,b=end===points.length-1?width-right:(x(end)+x(end+1))/2;return `<g class="altitude-date-band ${i%2?'is-even':''}"><rect x="${a}" y="112" width="${b-a}" height="${plotBottom-112}"/><line x1="${a}" y1="112" x2="${a}" y2="${plotBottom}"/><text x="${(a+b)/2}" y="132" text-anchor="middle"><tspan>${g.date}</tspan><tspan class="altitude-day"> · ${g.day}</tspan></text></g>`;}).join('');
    const markers=points.map((p,i)=>{const[px,py]=coords[i];return `<g class="altitude-marker ${p.stay?'is-stay':''}"><title>${p.date} ${esc(p.name)}，约${p.alt}米${p.stay?'，住宿点':''}</title><line class="altitude-stem" x1="${px}" y1="${py}" x2="${px}" y2="${plotBottom}"/><circle cx="${px}" cy="${py}" r="${p.stay?8:5}"/>${p.stay?`<text class="stay-badge" x="${px}" y="${py+3}" text-anchor="middle">住</text>`:''}<text class="altitude-value" x="${px}" y="${py-13}" text-anchor="middle">${p.alt.toLocaleString()}</text><text class="altitude-place" transform="translate(${px+2} ${labelY}) rotate(52)">${esc(p.name)}</text></g>`;}).join('');
    const highest=points.reduce((a,b)=>a.alt>b.alt?a:b),lowest=points.reduce((a,b)=>a.alt<b.alt?a:b);
    $('altitude-poster').innerHTML=`<article class="altitude-card"><header class="altitude-poster-head"><div><span class="altitude-kicker">ELEVATION PROFILE · A</span><h3>阿里中北线海拔曲线</h3><p>按每日行车顺序串联主要途经点；实心“住”为当晚住宿点。</p></div><dl><div><dt>最高点</dt><dd>${highest.alt.toLocaleString()} m</dd><small>${esc(highest.name)}</small></div><div><dt>最低点</dt><dd>${lowest.alt.toLocaleString()} m</dd><small>拉萨</small></div><div><dt>住宿节点</dt><dd>${points.filter(p=>p.stay).length}</dd><small>09.25—10.06</small></div></dl></header><div class="altitude-chart-scroll" tabindex="0" aria-label="可横向滚动查看完整海拔曲线"><svg class="altitude-svg" viewBox="0 0 ${width} ${height}" style="min-width:${width}px" role="img" aria-labelledby="altitude-title altitude-desc"><title id="altitude-title">阿里中北线逐日海拔曲线</title><desc id="altitude-desc">按日期展示主要途经点和住宿点的近似海拔，10月3日住尼玛。</desc><defs><linearGradient id="altitude-fill-classic" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1603a" stop-opacity=".3"/><stop offset="1" stop-color="#f1603a" stop-opacity=".03"/></linearGradient></defs><rect class="altitude-warning-zone" x="${left}" y="${plotTop}" width="${plotWidth}" height="${y(5000)-plotTop}"/>${bands}${grid}<path class="altitude-area" d="${area}" fill="url(#altitude-fill-classic)"/><path class="altitude-line" d="${line}"/>${markers}<text class="altitude-axis-note" x="${left}" y="${height-24}">横轴按路线节点顺序排列，不代表等距离；海拔沿用原攻略近似值。</text></svg></div><footer class="altitude-legend"><span><i class="legend-route"></i>途经点</span><span><i class="legend-stay">住</i>住宿点</span><span><i class="legend-high"></i>5,000 m 以上</span></footer></article>`;
  }
  function renderResearch(){
    $('choices-content').innerHTML=research.priorities.map(p=>`<article class="choice-card"><h3>${esc(p.category)}</h3><strong>优先保留</strong><b>${esc(p.keep)}</b><p><strong>可以舍弃 / 压缩</strong>${esc(p.optional)}</p><p>${esc(p.reason.replace('行程取舍建议：',''))}</p></article>`).join('');
    $('tickets-content').innerHTML=`<div class="ticket-list">${research.tickets.map(t=>`<article class="ticket-card"><span class="date-day">${esc(t.day)}</span><h3>${esc(t.name)}</h3><dl><dt>提前</dt><dd>${esc(t.booking)}</dd><dt>价格</dt><dd>${esc(t.price)}</dd><dt>渠道</dt><dd>${esc(t.channel)}</dd></dl><details><summary>开放、历史票价与行程提醒</summary><p>${esc(t.note)}</p></details>${link(t.url,'核验来源 ↗')}</article>`).join('')}</div>`;
    $('notes-content').innerHTML=research.notes.map(n=>`<article class="note-card"><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${link(n.url,'官方资料 ↗')}</article>`).join('');
    const resources=[...research.sources,...window.TIBET_MEDIA.sources,...window.TIBET_HOTEL_MEDIA.sources,...window.TIBET_EXTRA_MEDIA.sources];
    $('sources-content').innerHTML=`<h4>信息边界</h4><p>酒店字段完整沿用原攻略，不代表重新核实订单状态。D4、D5、D8、D9 的住宿起终点已更新，官方导航页面尚未取得完整新路线结果，车程明确待复核，不沿用旧数值。小红书链接均标为搜索入口，本版未获取笔记原文。</p><h4>照片与版权</h4><p>照片为实景资料，不代表出行当日季节与天气。两张 CC BY 2.0 授权照片保存为本地 WebP；其余使用来源网站的远程图片，版权归原作者。带明确授权限制的“大地之树”仅提供原文入口。远程图片需要联网，失效时不拿其他地点替代。</p><ul>${Object.values(media).filter(a=>a.src).map(a=>`<li>${link(a.sourceUrl,esc(a.name))} · ${esc(a.credit)}${a.licenseUrl?' · '+link(a.licenseUrl,esc(a.license||'许可')):''}</li>`).join('')}</ul><h4>公开资料</h4><ul>${resources.filter((r,i,all)=>r.url&&all.findIndex(x=>x.url===r.url)===i).map(r=>`<li>${link(r.url,esc(r.title||r.name||r.url))}${r.date?' · '+esc(r.date):''}</li>`).join('')}</ul><h4>天气口径</h4>${weather.notes.map(n=>`<p>${esc(n)}</p>`).join('')}`;
  }
  renderOverview();renderWeather();renderDays();renderDrone();renderHotels();renderAltitude();renderResearch();
  const hero=media[window.TIBET_MEDIA.hero];$('hero-credit').href=hero.sourceUrl;$('hero-credit').textContent=`${hero.credit} · 图经裁切 ↗`;
  document.querySelectorAll('.photo-wrap img').forEach(img=>{const fallback=img.parentElement.querySelector('.photo-fallback');const fail=()=>{img.hidden=true;fallback.hidden=false;};const loaded=()=>{img.hidden=false;fallback.hidden=true;};img.addEventListener('error',fail);img.addEventListener('load',loaded);if(img.complete&&img.naturalWidth)loaded();});
  $('print-guide').addEventListener('click',()=>window.print());
  const navLinks=[...document.querySelectorAll('.quick-nav a')];
  if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){navLinks.forEach(a=>{const active=a.hash===`#${entry.target.id}`;a.classList.toggle('is-active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}},{rootMargin:'-90px 0px -68% 0px',threshold:0});document.querySelectorAll('main>section[id]').forEach(s=>observer.observe(s));}
  // 可测试的数据与合并结果，只读供本地校验，不发起任何网络数据请求。
  window.TIBET_GUIDE_VIEW={mergedWeatherNodes:mergedWeatherNodes(),dayWeather};
})();
