'use strict';
(() => {
  const base=window.TIBET_BASE, guide=window.TIBET_ITINERARY, weather=window.TIBET_WEATHER, research=window.TIBET_RESEARCH;
  const media={...window.TIBET_MEDIA.assets,...window.TIBET_HOTEL_MEDIA.assets,...window.TIBET_EXTRA_MEDIA.assets};
  const hotelMedia=window.TIBET_HOTEL_MEDIA.hotels;
  const $=id=>document.getElementById(id);
  const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const lines=v=>esc(v).replace(/\n/g,'<br>');
  const link=(url,label,cls='')=>`<a href="${esc(url)}" class="${cls}" target="_blank" rel="noopener noreferrer">${label}</a>`;
  const findAsset=name=>Object.values(media).find(a=>a.name===name || (a.aliases||[]).includes(name));
  const hotelLink=h=>hotelMedia[h.hotel]?.url?link(hotelMedia[h.hotel].url,esc(h.hotel),'hotel-link'):esc(h.hotel);
  const weatherFor=day=>weather.nodes.filter(n=>n.day===day);
  const wxClass=c=>/雷/.test(c)?'storm':/雪/.test(c)?'snow':/雨/.test(c)?'rain':/阴/.test(c)?'overcast':/云/.test(c)?'cloud':'sun';
  const wxRank={sun:0,cloud:1,overcast:2,rain:3,snow:4,storm:5};
  const wxLabel={sun:'晴',cloud:'多云',overcast:'阴',rain:'雨',snow:'雨雪',storm:'雷雨'};
  function wxIcon(condition,size=30){
    if(!condition||condition==='待更新') return `<svg class="wx-icon" width="${size}" height="${size}" viewBox="0 0 40 40" role="img" aria-label="天气待更新"><circle cx="20" cy="20" r="13" fill="none" stroke="#8f998d" stroke-width="1.5" stroke-dasharray="3 3"/><text x="20" y="25" text-anchor="middle" fill="#8f998d" font-size="17">?</text></svg>`;
    const k=wxClass(condition),sun='<circle cx="19" cy="17" r="8" fill="#e7b550"/><path d="M19 3v3m0 22v3M5 17h3m22 0h3M9 7l2 2m16 16 2 2M9 27l2-2M27 9l2-2" stroke="#e7b550" stroke-width="2" stroke-linecap="round"/>',cloud='<path d="M10 27a7 7 0 0 1 0-14 10 10 0 0 1 18-1 8 8 0 1 1 2 15Z" fill="#c7d6d3" stroke="#7c9993" stroke-width="1.2"/>',rain='<path d="m12 30-2 5m11-5-2 5m11-5-2 5" stroke="#568cb1" stroke-width="2" stroke-linecap="round"/>',snow='<text x="11" y="38" font-size="14" fill="#568cb1">❄</text>',storm='<path d="m21 25-6 8h5l-2 6 9-10h-6l3-4" fill="#d89b3b"/>';
    return `<svg class="wx-icon" width="${size}" height="${size}" viewBox="0 0 40 40" role="img" aria-label="${esc(condition)}">${k==='sun'?sun:(k==='cloud'?sun:'')+cloud}${k==='rain'?rain:k==='snow'?snow:k==='storm'?storm:''}</svg>`;
  }
  function dayWeather(day){const all=weatherFor(day),valid=all.filter(n=>n.status==='forecast'&&Number.isFinite(n.high)&&Number.isFinite(n.low));if(!valid.length)return {available:false,condition:'待更新',text:'超出当前预报范围'};const worst=valid.reduce((a,n)=>wxRank[wxClass(n.condition)]>wxRank[wxClass(a.condition)]?n:a,valid[0]);return {available:true,high:Math.max(...valid.map(n=>n.high)),low:Math.min(...valid.map(n=>n.low)),condition:worst.condition,partial:valid.length!==all.length,text:`${wxLabel[wxClass(worst.condition)]} · ${valid.length!==all.length?'部分地点参考':'沿线参考范围'}`};}
  const rangeHtml=w=>`<div class="weather-range">${wxIcon(w.condition)}${w.available?`<span class="temp-stack"><span class="temp-high">${w.high}°C</span><span class="temp-low">${w.low}°C</span></span>`:'<span class="wx-summary">待更新</span>'}</div>`;
  function renderOverview(){
    $('overview-content').innerHTML=`<table class="overview-table"><thead><tr><th>日期</th><th>主要路线 / 节奏</th><th>住宿</th><th>天气温度</th><th>穿衣 / 随身重点</th></tr></thead><tbody>${guide.days.map(d=>{const w=dayWeather(d.day);return `<tr><td data-label="日期"><b>${d.date}</b><small class="date-day">${d.day} · ${d.weekday}</small></td><td data-label="路线"><div><p><a href="#day-${d.day}"><b>${d.route.join(' → ')}</b></a></p><small>${esc(d.pace)}</small></div></td><td data-label="住宿"><div>${d.hotelIndexes.length?d.hotelIndexes.map(i=>`${hotelLink(base.hotels[i])}${base.hotels[i].alert?` <span class="hotel-alert">（${esc(base.hotels[i].alert)}）</span>`:''}`).join('<br>'):'返程'}<small>${d.stay==='—'?'':esc(d.stay)}</small></div></td><td data-label="天气"><div>${rangeHtml(w)}<small>${esc(w.text)}</small></div></td><td data-label="穿衣"><div><p>${esc(d.clothing)}</p><small>随身：${esc(d.carry)}</small></div></td></tr>`;}).join('')}</tbody></table>`;
  }
  function mergedWeatherNodes(){
    const out=[];
    for(const n of weather.nodes){
      const prev=out.at(-1),valid=n.status==='forecast'&&Number.isFinite(n.high)&&Number.isFinite(n.low);
      const can=prev&&valid&&prev.status==='forecast'&&n.date===prev.date&&wxClass(n.condition)===prev.category&&Math.max(n.high,...prev.members.map(m=>m.high))-Math.min(n.high,...prev.members.map(m=>m.high))<=2&&Math.max(n.low,...prev.members.map(m=>m.low))-Math.min(n.low,...prev.members.map(m=>m.low))<=2;
      if(can){prev.members.push(n);prev.places.push(...n.places);prev.high=Math.max(prev.high,n.high);prev.low=Math.min(prev.low,n.low);}
      else out.push({...n,places:[...n.places],category:wxClass(n.condition),members:[n]});
    }
    return out;
  }
  function wrapLabel(s,max=13){const chars=[...s],out=[];for(let i=0;i<chars.length;i+=max)out.push(chars.slice(i,i+max).join(''));return out;}
  function renderWeather(){
    const nodes=mergedWeatherNodes(),valid=weather.nodes.filter(n=>n.status==='forecast'),w=Math.max(1200,nodes.length*146+95),h=480,left=58,right=30,top=100,bottom=297;
    const lo=Math.floor((Math.min(...valid.map(n=>n.low))-2)/5)*5,hi=Math.ceil((Math.max(...valid.map(n=>n.high))+2)/5)*5;
    const x=i=>left+(i+.5)*(w-left-right)/nodes.length,y=t=>bottom-(t-lo)/(hi-lo)*(bottom-top);
    let svg=`<svg class="weather-svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}" role="img" aria-labelledby="weather-title weather-desc"><title id="weather-title">沿途日期与地点高低温曲线</title><desc id="weather-desc">墨迹日期预报；红线最高温，蓝线日最低参考。未进入预报范围的日期不绘制数值。</desc>`;
    for(let v=lo;v<=hi;v+=5)svg+=`<line x1="${left}" y1="${y(v)}" x2="${w-right}" y2="${y(v)}" stroke="#d9dfd7" stroke-dasharray="3 5"/><text x="${left-12}" y="${y(v)+4}" text-anchor="end" font-size="11" fill="#7a897f">${v}°</text>`;
    let dayIndex=-1,lastDay='';nodes.forEach((n,i)=>{if(n.day!==lastDay){dayIndex++;lastDay=n.day;}const step=(w-left-right)/nodes.length;svg+=`<rect x="${x(i)-step/2}" y="12" width="${step}" height="450" fill="${dayIndex%2?'#153b3410':'transparent'}"/><text x="${x(i)}" y="34" text-anchor="middle" font-size="12" font-weight="700" fill="#234339">${n.date.slice(5).replace('-','.')} · ${n.day}</text><g transform="translate(${x(i)-17},44)">${wxIcon(n.condition,34)}</g>`;});
    for(const field of ['high','low']){let active=false,path='';nodes.forEach((n,i)=>{if(n.status!=='forecast'||!Number.isFinite(n[field])){active=false;return;}path+=`${active?'L':'M'}${x(i).toFixed(2)} ${y(n[field]).toFixed(2)} `;active=true;});svg+=`<path d="${path}" fill="none" stroke="${field==='high'?'#bd5d3e':'#427ea7'}" stroke-width="2.6" stroke-linejoin="round"/>`;}
    nodes.forEach((n,i)=>{if(n.status==='forecast'){for(const field of ['high','low']){svg+=`<circle cx="${x(i)}" cy="${y(n[field])}" r="4" fill="${field==='high'?'#bd5d3e':'#427ea7'}"/><text x="${x(i)}" y="${y(n[field])+(field==='high'?-12:21)}" text-anchor="middle" font-size="13" font-weight="700" fill="${field==='high'?'#a45032':'#3a7095'}">${n[field]}°</text>`;}}else svg+=`<text x="${x(i)}" y="196" text-anchor="middle" font-size="12" fill="#8a958d">待更新</text>`;
      const label=[...new Set(n.places)].join(' / ');svg+=`<text x="${x(i)}" y="344" text-anchor="middle" font-size="10" fill="#354f45">${wrapLabel(label).map((t,j)=>`<tspan x="${x(i)}" dy="${j?15:0}">${esc(t)}</tspan>`).join('')}</text><text x="${x(i)}" y="438" text-anchor="middle" font-size="9" fill="#758278">${esc([...new Set(n.members.map(m=>m.wind))].join(' / '))}</text>`;
    });svg+='</svg>';
    $('weather-stamp').innerHTML=`墨迹天气 · ${esc(weather.checkedAt.slice(0,16).replace('T',' '))}<br>静态预报快照，非自动更新`;
    $('weather-summary').innerHTML=`<div class="weather-note"><div><h3>9 月 25 日—10 月 3 日已有预报</h3><p>10 月 4—7 日待更新。沿途温区汇总取各点最高温最大值、最低温最小值；区县预报不等于山口、冰川、湖岸的精确温度。当前未取得出行日小时预报，蓝线为日最低温保守参考，不是 07:00—24:00 实际最低温。</p></div><span class="weather-badge">阴雨 · 低温 · 分层保暖</span></div>`;
    $('weather-chart').innerHTML=`<div class="chart-scroll" tabindex="0" aria-label="左右滚动查看全程天气曲线">${svg}</div><p class="chart-help"><span><i class="high"></i>最高温</span><span><i class="low"></i>日最低温参考</span><span>横向滑动看日期和地点 · 同日相邻相近天气合并</span></p>`;
    $('weather-detail').innerHTML=`<div class="weather-list">${weather.nodes.map(n=>`<article class="weather-source-card"><span class="date-day">${n.date} · ${n.day}</span><h4>${esc(n.places.join(' / '))}</h4><div class="reading">${esc(n.condition)} · ${n.status==='forecast'?`<b class="temp-high">${n.high}°C</b> / <b class="temp-low">${n.low}°C</b>`:'待更新'} · ${esc(n.wind)}</div><p>${esc(n.reason)}</p>${link(n.sourceUrl,`墨迹 · ${esc(n.region)} ↗`)}</article>`).join('')}</div><p class="micro">“转”表示白天到夜间的天气变化。合并仅发生于同日相邻地点、同天气类别且高低温分别相差不超过 2℃。</p>`;
  }
  function photo(a){
    if(!a?.src||a.requiresPermission||a.display==='source-link')return '';
    return `<div class="photo-wrap"><img src="${esc(a.src)}" alt="${esc(a.alt)}" loading="lazy" decoding="async" referrerpolicy="no-referrer"><div class="photo-fallback" hidden><b>图片暂不可用</b><span>文字攻略仍可阅读</span>${link(a.sourceUrl,'查看原图来源 ↗')}</div>${link(a.sourceUrl,esc(a.credit),'photo-credit')}</div>`;
  }
  function photoContext(a){
    if(!a)return '';
    if(a.name==='珠峰大本营')return '图：珠峰北坡／绒布寺一带，非营地设施实拍。';
    if(a.src==='guide-images/karuola.webp')return '图摄于 2011 年，冰川现状与照片可能不同。';
    if(a.license)return `${a.credit} · 图片经尺寸与格式调整`;
    return '';
  }
  function spotCard(s){const a=findAsset(s.name),xhs=`https://www.xiaohongshu.com/search_result?keyword=${encodeURIComponent(s.name+' 攻略')}`;return `<article class="photo-card">${photo(a)}<div class="photo-caption"><span class="card-tag">${esc(s.priority)} · ${esc(s.duration)}</span><h4>${esc(s.name)}</h4><p>${esc(s.play)}</p>${photoContext(a)?`<p class="photo-context">${esc(photoContext(a))}</p>`:''}${a?.requiresPermission?'<p class="photo-context">图源需转载授权，仅提供原文看图入口。</p>':''}<div class="card-links">${link(xhs,'小红书搜索 ↗','xhs-link')}${a?.sourceUrl?link(a.sourceUrl,a.requiresPermission?'原文看图 ↗':'图片来源 ↗'):''}${a?.licenseUrl?link(a.licenseUrl,'图片许可 ↗'):''}</div></div></article>`;}
  function hotelStrip(h){const a=media[hotelMedia[h.hotel]?.image]||findAsset(h.hotel);return `<aside class="hotel-strip">${photo(a)}<div class="hotel-summary"><p class="eyebrow">TONIGHT / 今晚住这里</p><h4>${hotelLink(h)}${h.alert?` <span class="hotel-alert">（${esc(h.alert)}）</span>`:''}</h4><p>${esc(h.span)} · ${lines(h.room)}<br>${esc(h.oxygen)} · 早餐：${esc(h.breakfast)}</p><div class="card-links"><a href="#hotels">查看房价与完整订单 ↗</a>${a?.sourceUrl?link(a.sourceUrl,'外景来源 ↗'):''}</div></div></aside>`;}
  function renderDays(){
    $('day-nav').innerHTML=guide.days.map(d=>`<a href="#day-${d.day}"><b>${d.day}</b>${d.date}</a>`).join('');
    $('days-content').innerHTML=guide.days.map(d=>{const w=dayWeather(d.day),spots=d.spots.map(k=>guide.spots[k]),photos=spots.filter(s=>s.priority!=='补给'),stops=spots.filter(s=>s.priority==='补给');return `<article class="day-article" id="day-${d.day}"><header class="day-heading"><div class="day-number">${d.day}<small>${d.date} · ${d.weekday}</small></div><div><p class="eyebrow">${esc(d.chapter)}</p><h3>${esc(d.title)}</h3><p class="route-line">${esc(d.route.join(' → '))}</p></div></header><div class="day-meta"><div><p><b>${esc(d.drive)}</b></p>${d.metricNote?`<p class="metric-note">${esc(d.metricNote)}</p>`:''}<small>${esc(d.pace)}</small></div><div class="day-weather">${rangeHtml(w)}<div class="day-weather-text"><b>${esc(w.text)}</b><br>${esc(d.clothing)}</div></div></div>${photos.length?`<div class="photo-grid count-${photos.length}">${photos.map(spotCard).join('')}</div>`:''}${stops.map(s=>`<div class="stop-text"><b>${esc(s.name)} · ${esc(s.duration)}</b><p>${esc(s.play)}</p></div>`).join('')}${d.hotelIndexes.map(i=>hotelStrip(base.hotels[i])).join('')}<div class="schedule" aria-label="${d.day}建议时间安排">${d.schedule.map(row=>`<div class="schedule-row"><time>${esc(row[0])}</time><h4>${esc(row[1])}</h4><p>${esc(row[2])}</p></div>`).join('')}</div><div class="day-decision"><b>当天取舍</b><p>${esc(d.decision)}</p></div></article>`;}).join('');
  }
  function renderHotels(){
    const counts=base.hotels.reduce((m,h)=>m.set(h.checkin,(m.get(h.checkin)||0)+1),new Map()),seen=new Set();
    const rows=base.hotels.map(h=>{const date=seen.has(h.checkin)?'':`<td class="nowrap hotel-date" rowspan="${counts.get(h.checkin)}"><strong>${lines(h.checkin)}</strong></td>`;seen.add(h.checkin);const backup=h.place.endsWith('（备选）'),place=backup?h.place.slice(0,-4):h.place;return `<tr>${date}<td class="nowrap">${esc(h.span)}</td><td>${esc(place)}${backup?' <span class="hotel-backup">（备选）</span>':''}${h.alert?` <span class="hotel-alert">（${esc(h.alert)}）</span>`:''}</td><td class="hotel-name"><strong>${hotelLink(h)}</strong></td><td><strong>${lines(h.price)}</strong></td><td>${lines(h.room)}</td><td class="nowrap">${esc(h.cancel)}</td><td class="nowrap">${lines(h.area)}</td><td>${lines(h.bed)}</td><td>${esc(h.oxygen)}</td><td>${esc(h.breakfast)}</td></tr>`;}).join('');
    $('hotel-grid').innerHTML=`<div class="hotel-table-wrap" tabindex="0" aria-label="可横向滚动的酒店完整信息表"><table class="hotel-table"><thead><tr>${['入住日','晚数 / 间数','地点','酒店名','单间价格','房型','可取消时间','面积','床型','供氧方式','早餐'].map(v=>`<th scope="col">${v}</th>`).join('')}</tr></thead><tbody>${rows}</tbody></table></div>`;
  }
  function renderAltitude(){
    const groups=base.profile,points=groups.flatMap((g,groupIndex)=>g.points.map(p=>({...p,date:g.date,day:g.day,groupIndex}))),width=Math.max(1680,points.length*74+150),height=690,left=74,right=42,plotTop=150,plotBottom=470,labelY=505,plotWidth=width-left-right;
    const x=i=>left+i*plotWidth/(points.length-1),y=a=>plotBottom-(a-3400)/(5400-3400)*(plotBottom-plotTop),coords=points.map((p,i)=>[x(i),y(p.alt)]);
    const line=coords.map(([px,py],i)=>`${i?'L':'M'} ${px.toFixed(1)} ${py.toFixed(1)}`).join(' '),area=`${line} L ${coords.at(-1)[0]} ${plotBottom} L ${coords[0][0]} ${plotBottom} Z`;
    const grid=[3500,4000,4500,5000].map(t=>`<g class="altitude-grid-line"><line x1="${left}" y1="${y(t)}" x2="${width-right}" y2="${y(t)}"/><text x="${left-14}" y="${y(t)+4}" text-anchor="end">${t.toLocaleString()} m</text></g>`).join('');
    let offset=0;const bands=groups.map((g,i)=>{const start=offset,end=offset+g.points.length-1;offset+=g.points.length;const a=start===0?left:(x(start-1)+x(start))/2,b=end===points.length-1?width-right:(x(end)+x(end+1))/2;return `<g class="altitude-date-band ${i%2?'is-even':''}"><rect x="${a}" y="112" width="${b-a}" height="${plotBottom-112}"/><line x1="${a}" y1="112" x2="${a}" y2="${plotBottom}"/><text x="${(a+b)/2}" y="132" text-anchor="middle"><tspan>${g.date}</tspan><tspan class="altitude-day"> · ${g.day}</tspan></text></g>`;}).join('');
    const markers=points.map((p,i)=>{const[px,py]=coords[i];return `<g class="altitude-marker ${p.stay?'is-stay':''}"><title>${p.date} ${esc(p.name)}，约${p.alt}米${p.stay?'，住宿点':''}</title><line class="altitude-stem" x1="${px}" y1="${py}" x2="${px}" y2="${plotBottom}"/><circle cx="${px}" cy="${py}" r="${p.stay?8:5}"/>${p.stay?`<text class="stay-badge" x="${px}" y="${py+3}" text-anchor="middle">住</text>`:''}<text class="altitude-value" x="${px}" y="${py-13}" text-anchor="middle">${p.alt.toLocaleString()}</text><text class="altitude-place" transform="translate(${px+2} ${labelY}) rotate(52)">${esc(p.name)}</text></g>`;}).join('');
    const highest=points.reduce((a,b)=>a.alt>b.alt?a:b),lowest=points.reduce((a,b)=>a.alt<b.alt?a:b);
    $('altitude-poster').innerHTML=`<article class="altitude-card"><header class="altitude-poster-head"><div><span class="altitude-kicker">ELEVATION PROFILE · A</span><h3>阿里中北线海拔曲线</h3><p>按每日行车顺序串联主要途经点；实心“住”为当晚住宿点。</p></div><dl><div><dt>最高点</dt><dd>${highest.alt.toLocaleString()} m</dd><small>${esc(highest.name)}</small></div><div><dt>最低点</dt><dd>${lowest.alt.toLocaleString()} m</dd><small>拉萨</small></div><div><dt>住宿节点</dt><dd>${points.filter(p=>p.stay).length}</dd><small>09.25—10.06</small></div></dl></header><div class="altitude-chart-scroll" tabindex="0" aria-label="可横向滚动查看完整海拔曲线"><svg class="altitude-svg" viewBox="0 0 ${width} ${height}" style="min-width:${width}px" role="img" aria-labelledby="altitude-title altitude-desc"><title id="altitude-title">阿里中北线逐日海拔曲线</title><desc id="altitude-desc">按日期展示主要途经点和住宿点的近似海拔，10月3日住尼玛。</desc><defs><linearGradient id="altitude-fill-classic" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="#f1603a" stop-opacity=".3"/><stop offset="1" stop-color="#f1603a" stop-opacity=".03"/></linearGradient></defs><rect class="altitude-warning-zone" x="${left}" y="${plotTop}" width="${plotWidth}" height="${y(5000)-plotTop}"/>${bands}${grid}<path class="altitude-area" d="${area}" fill="url(#altitude-fill-classic)"/><path class="altitude-line" d="${line}"/>${markers}<text class="altitude-axis-note" x="${left}" y="${height-24}">横轴按路线节点顺序排列，不代表等距离；海拔沿用原攻略近似值。</text></svg></div><footer class="altitude-legend"><span><i class="legend-route"></i>途经点</span><span><i class="legend-stay">住</i>住宿点</span><span><i class="legend-high"></i>5,000 m 以上</span></footer></article>`;
  }
  function renderResearch(){
    $('choices-content').innerHTML=research.priorities.map(p=>`<article class="choice-card"><h3>${esc(p.category)}</h3><strong>优先保留</strong><b>${esc(p.keep)}</b><p><strong>可以舍弃 / 压缩</strong>${esc(p.optional)}</p><p>${esc(p.reason.replace('行程取舍建议：',''))}</p></article>`).join('');
    $('tickets-content').innerHTML=`<div class="ticket-list">${research.tickets.map(t=>`<article class="ticket-card"><span class="date-day">${esc(t.day)}</span><h3>${esc(t.name)}</h3><dl><dt>提前</dt><dd>${esc(t.booking)}</dd><dt>价格</dt><dd>${esc(t.price)}</dd><dt>渠道</dt><dd>${esc(t.channel)}</dd></dl><details><summary>开放、历史票价与行程提醒</summary><p>${esc(t.note)}</p></details>${link(t.url,'核验来源 ↗')}</article>`).join('')}</div>`;
    $('notes-content').innerHTML=research.notes.map(n=>`<article class="note-card"><h3>${esc(n.title)}</h3><p>${esc(n.text)}</p>${link(n.url,'官方资料 ↗')}</article>`).join('');
    const resources=[...research.sources,...window.TIBET_MEDIA.sources,...window.TIBET_EXTRA_MEDIA.sources];
    $('sources-content').innerHTML=`<h4>信息边界</h4><p>酒店字段完整沿用原攻略，不代表重新核实订单状态。D4、D5、D8、D9 的住宿起终点已更新，官方导航页面尚未取得完整新路线结果，车程明确待复核，不沿用旧数值。小红书链接均标为搜索入口，本版未获取笔记原文。</p><h4>照片与版权</h4><p>照片为实景资料，不代表出行当日季节与天气。两张 CC BY 2.0 授权照片保存为本地 WebP；其余使用来源网站的远程图片，版权归原作者。带明确授权限制的“大地之树”仅提供原文入口。远程图片需要联网，失效时不拿其他地点替代。</p><ul>${Object.values(media).filter(a=>a.src).map(a=>`<li>${link(a.sourceUrl,esc(a.name))} · ${esc(a.credit)}${a.licenseUrl?' · '+link(a.licenseUrl,esc(a.license||'许可')):''}</li>`).join('')}</ul><h4>公开资料</h4><ul>${resources.filter((r,i,all)=>r.url&&all.findIndex(x=>x.url===r.url)===i).map(r=>`<li>${link(r.url,esc(r.title||r.name||r.url))}${r.date?' · '+esc(r.date):''}</li>`).join('')}</ul><h4>天气口径</h4>${weather.notes.map(n=>`<p>${esc(n)}</p>`).join('')}`;
  }
  renderOverview();renderWeather();renderDays();renderHotels();renderAltitude();renderResearch();
  const hero=media[window.TIBET_MEDIA.hero];$('hero-credit').href=hero.sourceUrl;$('hero-credit').textContent=`${hero.credit} · 图经裁切 ↗`;
  document.querySelectorAll('.photo-wrap img').forEach(img=>{const fallback=img.parentElement.querySelector('.photo-fallback');const fail=()=>{img.hidden=true;fallback.hidden=false;};const loaded=()=>{img.hidden=false;fallback.hidden=true;};img.addEventListener('error',fail);img.addEventListener('load',loaded);if(img.complete&&img.naturalWidth)loaded();});
  $('print-guide').addEventListener('click',()=>window.print());
  const navLinks=[...document.querySelectorAll('.quick-nav a')];
  if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>{for(const entry of entries)if(entry.isIntersecting){navLinks.forEach(a=>{const active=a.hash===`#${entry.target.id}`;a.classList.toggle('is-active',active);if(active)a.setAttribute('aria-current','location');else a.removeAttribute('aria-current');});}},{rootMargin:'-90px 0px -68% 0px',threshold:0});document.querySelectorAll('main>section[id]').forEach(s=>observer.observe(s));}
  // 可测试的数据与合并结果，只读供本地校验，不发起任何网络数据请求。
  window.TIBET_GUIDE_VIEW={mergedWeatherNodes:mergedWeatherNodes(),dayWeather};
})();
